/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.marklogic.kafka.connect.sink;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroTestClass extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 1401059904506924244L;


    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroTestClass\",\"namespace\":\"com.marklogic.kafka.connect.sink\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"luckyNumber\",\"type\":\"int\"},{\"name\":\"enabled\",\"type\":\"boolean\",\"default\":true}]}");
    public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<com.marklogic.kafka.connect.sink.AvroTestClass> ENCODER =
        new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<com.marklogic.kafka.connect.sink.AvroTestClass> DECODER =
        new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<com.marklogic.kafka.connect.sink.AvroTestClass> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<com.marklogic.kafka.connect.sink.AvroTestClass> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<com.marklogic.kafka.connect.sink.AvroTestClass> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this AvroTestClass to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a AvroTestClass from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a AvroTestClass instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static com.marklogic.kafka.connect.sink.AvroTestClass fromByteBuffer(
        java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private java.lang.String name;
    private int luckyNumber;
    private boolean enabled;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public AvroTestClass() {}

    /**
     * All-args constructor.
     * @param name The new value for name
     * @param luckyNumber The new value for luckyNumber
     * @param enabled The new value for enabled
     */
    public AvroTestClass(java.lang.String name, java.lang.Integer luckyNumber, java.lang.Boolean enabled) {
        this.name = name;
        this.luckyNumber = luckyNumber;
        this.enabled = enabled;
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

    @Override
    public org.apache.avro.Schema getSchema() { return SCHEMA$; }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0: return name;
            case 1: return luckyNumber;
            case 2: return enabled;
            default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value="unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0: name = value$ != null ? value$.toString() : null; break;
            case 1: luckyNumber = (java.lang.Integer)value$; break;
            case 2: enabled = (java.lang.Boolean)value$; break;
            default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'name' field.
     * @return The value of the 'name' field.
     */
    public java.lang.String getName() {
        return name;
    }


    /**
     * Sets the value of the 'name' field.
     * @param value the value to set.
     */
    public void setName(java.lang.String value) {
        this.name = value;
    }

    /**
     * Gets the value of the 'luckyNumber' field.
     * @return The value of the 'luckyNumber' field.
     */
    public int getLuckyNumber() {
        return luckyNumber;
    }


    /**
     * Sets the value of the 'luckyNumber' field.
     * @param value the value to set.
     */
    public void setLuckyNumber(int value) {
        this.luckyNumber = value;
    }

    /**
     * Gets the value of the 'enabled' field.
     * @return The value of the 'enabled' field.
     */
    public boolean getEnabled() {
        return enabled;
    }


    /**
     * Sets the value of the 'enabled' field.
     * @param value the value to set.
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Creates a new AvroTestClass RecordBuilder.
     * @return A new AvroTestClass RecordBuilder
     */
    public static com.marklogic.kafka.connect.sink.AvroTestClass.Builder newBuilder() {
        return new com.marklogic.kafka.connect.sink.AvroTestClass.Builder();
    }

    /**
     * Creates a new AvroTestClass RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new AvroTestClass RecordBuilder
     */
    public static com.marklogic.kafka.connect.sink.AvroTestClass.Builder newBuilder(com.marklogic.kafka.connect.sink.AvroTestClass.Builder other) {
        if (other == null) {
            return new com.marklogic.kafka.connect.sink.AvroTestClass.Builder();
        } else {
            return new com.marklogic.kafka.connect.sink.AvroTestClass.Builder(other);
        }
    }

    /**
     * Creates a new AvroTestClass RecordBuilder by copying an existing AvroTestClass instance.
     * @param other The existing instance to copy.
     * @return A new AvroTestClass RecordBuilder
     */
    public static com.marklogic.kafka.connect.sink.AvroTestClass.Builder newBuilder(com.marklogic.kafka.connect.sink.AvroTestClass other) {
        if (other == null) {
            return new com.marklogic.kafka.connect.sink.AvroTestClass.Builder();
        } else {
            return new com.marklogic.kafka.connect.sink.AvroTestClass.Builder(other);
        }
    }

    /**
     * RecordBuilder for AvroTestClass instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<com.marklogic.kafka.connect.sink.AvroTestClass>
        implements org.apache.avro.data.RecordBuilder<com.marklogic.kafka.connect.sink.AvroTestClass> {

        private java.lang.String name;
        private int luckyNumber;
        private boolean enabled;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.marklogic.kafka.connect.sink.AvroTestClass.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.name)) {
                this.name = data().deepCopy(fields()[0].schema(), other.name);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.luckyNumber)) {
                this.luckyNumber = data().deepCopy(fields()[1].schema(), other.luckyNumber);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.enabled)) {
                this.enabled = data().deepCopy(fields()[2].schema(), other.enabled);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
        }

        /**
         * Creates a Builder by copying an existing AvroTestClass instance
         * @param other The existing instance to copy.
         */
        private Builder(com.marklogic.kafka.connect.sink.AvroTestClass other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.name)) {
                this.name = data().deepCopy(fields()[0].schema(), other.name);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.luckyNumber)) {
                this.luckyNumber = data().deepCopy(fields()[1].schema(), other.luckyNumber);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.enabled)) {
                this.enabled = data().deepCopy(fields()[2].schema(), other.enabled);
                fieldSetFlags()[2] = true;
            }
        }

        /**
         * Gets the value of the 'name' field.
         * @return The value.
         */
        public java.lang.String getName() {
            return name;
        }


        /**
         * Sets the value of the 'name' field.
         * @param value The value of 'name'.
         * @return This builder.
         */
        public com.marklogic.kafka.connect.sink.AvroTestClass.Builder setName(java.lang.String value) {
            validate(fields()[0], value);
            this.name = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'name' field has been set.
         * @return True if the 'name' field has been set, false otherwise.
         */
        public boolean hasName() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'name' field.
         * @return This builder.
         */
        public com.marklogic.kafka.connect.sink.AvroTestClass.Builder clearName() {
            name = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'luckyNumber' field.
         * @return The value.
         */
        public int getLuckyNumber() {
            return luckyNumber;
        }


        /**
         * Sets the value of the 'luckyNumber' field.
         * @param value The value of 'luckyNumber'.
         * @return This builder.
         */
        public com.marklogic.kafka.connect.sink.AvroTestClass.Builder setLuckyNumber(int value) {
            validate(fields()[1], value);
            this.luckyNumber = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'luckyNumber' field has been set.
         * @return True if the 'luckyNumber' field has been set, false otherwise.
         */
        public boolean hasLuckyNumber() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'luckyNumber' field.
         * @return This builder.
         */
        public com.marklogic.kafka.connect.sink.AvroTestClass.Builder clearLuckyNumber() {
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'enabled' field.
         * @return The value.
         */
        public boolean getEnabled() {
            return enabled;
        }


        /**
         * Sets the value of the 'enabled' field.
         * @param value The value of 'enabled'.
         * @return This builder.
         */
        public com.marklogic.kafka.connect.sink.AvroTestClass.Builder setEnabled(boolean value) {
            validate(fields()[2], value);
            this.enabled = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'enabled' field has been set.
         * @return True if the 'enabled' field has been set, false otherwise.
         */
        public boolean hasEnabled() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'enabled' field.
         * @return This builder.
         */
        public com.marklogic.kafka.connect.sink.AvroTestClass.Builder clearEnabled() {
            fieldSetFlags()[2] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public com.marklogic.kafka.connect.sink.AvroTestClass build() {
            try {
                com.marklogic.kafka.connect.sink.AvroTestClass record = new com.marklogic.kafka.connect.sink.AvroTestClass();
                record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
                record.luckyNumber = fieldSetFlags()[1] ? this.luckyNumber : (java.lang.Integer) defaultValue(fields()[1]);
                record.enabled = fieldSetFlags()[2] ? this.enabled : (java.lang.Boolean) defaultValue(fields()[2]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<com.marklogic.kafka.connect.sink.AvroTestClass>
        WRITER$ = (org.apache.avro.io.DatumWriter<com.marklogic.kafka.connect.sink.AvroTestClass>)MODEL$.createDatumWriter(SCHEMA$);

    @Override public void writeExternal(java.io.ObjectOutput out)
        throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<com.marklogic.kafka.connect.sink.AvroTestClass>
        READER$ = (org.apache.avro.io.DatumReader<com.marklogic.kafka.connect.sink.AvroTestClass>)MODEL$.createDatumReader(SCHEMA$);

    @Override public void readExternal(java.io.ObjectInput in)
        throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override protected boolean hasCustomCoders() { return true; }

    @Override public void customEncode(org.apache.avro.io.Encoder out)
        throws java.io.IOException
    {
        out.writeString(this.name);

        out.writeInt(this.luckyNumber);

        out.writeBoolean(this.enabled);

    }

    @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
        throws java.io.IOException
    {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.name = in.readString();

            this.luckyNumber = in.readInt();

            this.enabled = in.readBoolean();

        } else {
            for (int i = 0; i < 3; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.name = in.readString();
                        break;

                    case 1:
                        this.luckyNumber = in.readInt();
                        break;

                    case 2:
                        this.enabled = in.readBoolean();
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}










